### ISSUE TITLE
Graphique journalier

### ISSUE THREAD

**Issue by bbrangeo** [stawen/okovision#115]
Bonjour, je n'arrive pas à ajouter un 2eme graphique journaliers personnalisés car la liste déroulante "Graphique" ne me le permet pas. En clair, je ne peux pas Affectation un capteur dans ce un nouveau graphique.

<img width="625" alt="Capture d’écran 2021-01-23 à 09 03 36" src="https://user-images.githubusercontent.com/769760/105572907-3c988380-5d5a-11eb-9ca0-1c09d8d14578.png">

Merci

**Comment by stawen** [comment]
tu dois le choisir comme indiqué dans le doc

![image](https://user-images.githubusercontent.com/13132210/105576198-71fc9b80-5d71-11eb-9694-ce82d58e8386.png)

http://okovision.dronek.com/wiki.html#!/md/manageGraphics.md#Ajout_des_capteurs_au_graphique

**Comment by bbrangeo** [comment]
Salut,

Je t'assure que je suis la doc, et après avoir filtré pour choisir mon nouveau graphe, je ne peux pas sélectionner celui-ci 

<img width="1080" alt="Capture d’écran 2021-01-24 à 18 17 35" src="https://user-images.githubusercontent.com/769760/105637952-70fe6380-5e70-11eb-8ad8-ff476a9e8eac.png">

**Comment by bbrangeo** [comment]
C'est bon j'ai compris. Je suis sur Safari et sur chrome ca fonctionne.
