### ISSUE TITLE
partition DSM remplie

### ISSUE THREAD

**Issue by victo62** [stawen/okovision#117]
salut,
merci bcp pour cette application que j'ai récemment installée sur mon NAS synology.
Cela fonctionnait très bien jusqu'au moment où j'ai perdu l'accès à mon NAS suite à la partition système pleine.
Suite à l'analyse du SAV Synology, ils ont identifié que des fichiers générés par Okovision venaient remplir cette partition et au final bloquer le système. Ces fichiers devraient être stockés dans le volume1.
Est il normal que des fichiers soient stockés dans la partition DSM?
Est il possible de modifier l'adresse de stockage des fichiers?
merci

**Comment by stawen** [comment]
salut,
peux tu etre plus precis ? de quel fichier tu parles exactement ? quels fichiers ont été rempli par okovision ? est-ce des fichiers systemes ou okovision.log ?

**Comment by victo62** [comment]
salut,
j'ai contacté le support de Synology pour avoir davantage d'infos
Il s'agissait de fichiers cron.php
![image](https://user-images.githubusercontent.com/81487432/112886456-4039e500-90d2-11eb-8a5e-eedc1c230d01.png)
![image](https://user-images.githubusercontent.com/81487432/112886505-5051c480-90d2-11eb-988e-ea13037f4750.png)

La tâche planifiée était affectée au root, je vais l'affecter à mon user en
espérant que cela ne remplisse plus la partition DSM mais le volume1.
Par ailleurs, la taille des fichiers #187 et #188 est énorme (bug??).

**Comment by stawen** [comment]
Salut,

Il n'est pas prévu dans le code de générer des fichier cron comme cela est montré dans tes images. 
Sur les autres installations sur syno, cela marche bien. 
Le seul fichier de log okovision.log est bien généré sur le volume1.

Je ne sais pas comment tu as fais ton installation. Refait la en suivant la doc.

Je clos le ticket car cela n'est pas lié au code.
