### ISSUE TITLE
mariadb10

### ISSUE THREAD

**Issue by victo62** [stawen/okovision#118]
Bonjour,
Vu que Mariadb5 n'est plus fonctionnel sous DSM7 je souhaiterais savoir si le support de Mariadb10 est prévu
merci

**Comment by stawen** [comment]
Okovision fonctionne sans souci avec MariaDb 10. Je l'utilise sur mon DSM6 depuis plusieurs années

**Comment by victo62** [comment]
Dans phpmyadmin j'ai importé la base MariaDB5 dans le serveur MariaDB10
Puis j'ai désinstallé MariaDB5 mais lorsque je lance okovision ça charge en boucle
Lorsque je réinstalle Mariadb5 ça fonctionne à nouveau
Quelle étape ai je ratée?

**Comment by victo62** [comment]
dans le log j'ai
03.07.2021 | 11:14:27 | ERROR   | GLOBAL | Connection MySQL impossible : No such file or directory

**Comment by stawen** [comment]
es-tu sur que mariadb10 demarre bien sur le meme port que la version 5 ? 
Car ton erreur indique qu'il ne voit pas la base.

Normalement le port est 3306, dans ma config j'ai le port 3307 car j'avais maria5 et 10 en //.
Regarde la config de ton maria10 sur ton interface d'admin de ton syno

![image](https://user-images.githubusercontent.com/13132210/124351437-91d69c00-dbfa-11eb-9952-ecc5f2ca1c57.png)

Dans okovision tu vas dans le fichier de `config.php`

![image](https://user-images.githubusercontent.com/13132210/124351491-ee39bb80-dbfa-11eb-9596-55c8e2940375.png)

**Comment by victo62** [comment]
nickel
après ajout du port dans le fichier config et activation de la connexion TCP/IP sous MariaDB10 (pas activée pas défaut contrairement à la v5) ça fonctionne
merci pour ton aide
