### ISSUE TITLE
Graph Journallier se termine à 22h12 

### ISSUE THREAD

**Issue by ffwill** [stawen/okovision#33]
Installation par default sur NAS synology.
Controle d'une Pelematic Smart.

L'import de donnée, (ou le graph) se termine à 22h12, pour tous les jours

Par example les données du 2015-05-10:
![capture du 2015-10-07 08 09 21](https://cloud.githubusercontent.com/assets/15009548/10330277/635042f4-6ccb-11e5-9d3d-8b7a10754e06.png)

Avec le fichier CSV suivant:
(impossible a envoyer format inconu, ne veux ni en zip ni en .txt, et openOffice crash a la transformation en XLSX^^)

Sinon Je t'avais déja donnée un fichier sur futura-science:
http://forums.futura-sciences.com/habitat-bioclimatique-isolation-chauffage/568807-retours-dexperiences-chaudieres-okofen-354.html#post5296828

**Comment by stawen** [comment]
juste pour info, tu es bien en derniere version 1.3.1 ? Pour que je test avec la meme version

**Comment by stawen** [comment]
Autre question, le firmware de ta chaudiere a-t-il été mis a jour dernierement ? (Apres l'apprentissage de la matrice par Okovision ) ?

**Comment by stawen** [comment]
je viens de faire un test avec le fichier que tu m'avais transmis (fichier du 02/08/2015)

![image](https://cloud.githubusercontent.com/assets/13132210/10336075/6978b2bc-6cf6-11e5-9f2b-4dd7cabc28f2.png)

pas de prob.

Je pense que ton souci vient du cron, tu as peut etre un param qui ne va pas.

regarde bien dans le wiki les param du Cron

https://github.com/stawen/okovision/wiki/2.bis-Installation-sur-un-NAS-Synology

As-tu la synthèse journalière qui se fait automatiquement ? Si non, cela veut dire que le cron n'est pas executé à 00hxx

**Comment by stawen** [comment]
si tu fais un import manuel, tu as toutes les données ?

**Comment by stawen** [comment]
Vu dans le forum
http://forums.futura-sciences.com/logiciel-software-open-source/705908-okovision-retours-utilisateurs-7.html#post5359478

J'attend confirmation pour Clore le ticket

**Comment by ffwill** [comment]
Bonsoir Stawen,

Ce n'est pas l'import pour la Cron dont j'ai fait le rapport, c'est bien import: "Mise à jour des données (depuis chaudiere)"
(j'ai quelques problème avec la CRON, dont je pense à 90% chez moi, j'aurai pas créer un ticket pour ça)

Par contre effectivement, J’étais bien en version 1.3.0, je viens de faire la mise à jour.

Et j'ai pu importer la journée d'hier au complet sans problème. Donc a priori ça m'a l'aire bon.
Alors que avant hier, hier et ce matin impossible de charger la mise a jour de la vielle jusqu'a 24h.... 
Etrange....
