### ISSUE TITLE
P1 - CRON - test If 23h59

### ISSUE THREAD

**Issue by stawen** [stawen/okovision#37]
lors de la cron, si pas 00h, tester les fichiers jusqua J-4 pour voir si 23h59 existe, si non, on importe les journées incomplete.
Si 00h, idem mais avec j-3

**Comment by stawen** [comment]
je viens de lire le code, ça me semble pas mal. je vais le tester dans la semaine avant de l’intégrer dans la branche unstable

**Comment by bertrandgorge** [comment]
Des nouvelles ? :-)
