### ISSUE TITLE
bloquer l'import en doublon http / usb

### ISSUE THREAD

**Issue by stawen** [stawen/okovision#70]
Si on importe en http, il est possible d'importer aussi pour la meme journé en usb. le prob est que les minutes de mesure sont légrement differentes, donc elles sont insérées en base. Et créé des doublons.

exemple de log

**Comment by stawen** [comment]
[touch_log_csv.zip](https://github.com/stawen/okovision/files/90080/touch_log_csv.zip)

**Comment by bertrandgorge** [comment]
Hum, épatant. J'ai regardé ce que ma chaudière faisait, et les time stamps sont les mêmes - en revanche les valeurs ne le sont pas - pour quelque étrange raison, la version web et la version USB diffèrent en plein d'endroits, températures, etc... Bref, l'erreur doit se compenser dans le volume.

Pour le cas où les fichiers n'ont pas la même heure, il n'y a que deux options il me semble : 
- Option 1 : on change la clé primaire pour utiliser le timestamp, et avant de créer le timestamp on arrondi les secondes. Ainsi, si on importe deux fichiers avec les mêmes heures, les lignes seront simplement ignorées par le INSERT IGNORE. Le seul soucis avec cette méthode, c'est que si la chaudière est réglée pour faire des lignes de data toutes les 10 secondes au lieu de toutes les minutes, on va ignorer plein de lignes utiles. Après, ça peut être un pré-requis d'Okovision que d'avoir un réglage à la minute.
- Option 2 : avant d'insérer un fichier, on prend les deux timestamps min et max du fichier, et on supprime toutes les lignes entre ces dates déjà en DB avant d'importer le nouveau. Au passage il faut supprimer la synthèse annuelle si elle existe déjà...?

**Comment by stawen** [comment]
Option 1 : dans le dernier Firmware Okofen, iil genere tjrs un log toutes les minutes, donc cette methode me semble aussi la plus simple.
Il faut arrondire les secondes de chaque minute pour les mettre à 00
