### ISSUE TITLE
Bug accès espace sécurisé

### ISSUE THREAD

**Issue by Thorketil** [stawen/okovision#80]
Utilisateur de Firefox, j'avais systématiquement des fenêtres d'erreur "problème de connexion : admin login"  lorsque je voulais me connecter.
Et la fenêtre de connexion ne disparaissait pas même une fois connecté.
J'ai l'impression que ces problèmes ont disparu sur FF suite à un essai de connexion sur edge...

En revanche je n'arrive toujours pas à me déconnecter sur FF alors que sur edge, oui:
![image](https://cloud.githubusercontent.com/assets/18676213/22061903/5abbe8be-dd77-11e6-9d27-a913419b639a.png)

De plus je n'arrive  pas à modifier mon mot de passe, le changement n'est pas pris en compte.

**Comment by stawen** [comment]
bjr,

effectivement, pris en compte

**Comment by epelissot** [comment]
Boujour Stawen,
Je crains que le problème soit toujours là chez moi...toujours pas possible de changer le mdp ni de déconnecter "proprement" sur FF.
Du coup j'ai quand même pu changer mon mdp, mais en utilisant edge.
