### ISSUE TITLE
L'installation ne fonctionne pas en hébergement mutualisé OVH (le cron ne se lance pas)

### ISSUE THREAD

**Issue by bertrandgorge** [stawen/okovision#83]
La tâche cron.php n'arrive pas à s’exécuter sur les hébergement web mutualisés OVH, à cause de la manière dont les includes sont faits. En gros, il faut inclure tout avec un chemin en absolu parce que via cron, le dossier courant n'est pas ajouté aux include_paths (cf doc https://docs.ovh.com/fr/hosting/mutualise-taches-automatisees-cron/)

J'ouvre ce bug pour pouvoir le fermer après (le fix est rapide).

**Comment by stawen** [comment]
corrigé dans le version 1.8.3
