### ISSUE TITLE
Distinguer le bois utilisé pour le chauffe-eau vs celui utilisé pour le chauffage

### ISSUE THREAD

**Issue by bertrandgorge** [stawen/okovision#85]
En se basant sur la moyenne (glissante) de la consommation de bois, les jours où il n'y a pas de chauffage (et donc que du chauffe eau), on peut en déduire la part prise par le chauffage vs le chauffe eau. Ca permet, sur les rapports mensuels, de mieux calculer l'impact des changements de réglage ou d'isolation.

**Comment by stawen** [comment]
Fait : 
  - Se baser sur le param ww[x].pumpe (circulateur ECS) qui déclenche l'utilisation de la chaudière à la génération d'eau chaude.
  - sur la page d'accueil, ajout de la conso ECS 
![image](https://user-images.githubusercontent.com/13132210/100731089-37a6fb80-33cb-11eb-8aa4-e0ef2bb33d30.png)

A finir : 
  - dans graphe resumé par jour, voir si afficher : 
    - conso total et ECS,
    - ou conso chauffage et ECS, 
    - ou conso chauffage et ECS et total

- voir si l'Inclure dans le meme graphe (peut etre lourd visuellement) barre graphe, etc

**Comment by bertrandgorge** [comment]
Si je comprends bien finalement ce que tu fais, c'est de compter la consommation quand la pompe ECS tourne, c'est ça ? Mais du coup si la pompe de chauffage tourne en même temps que celle de l'ECS, on aura une lecture un peu biaisée, non ?

Ma solution n'est pas idéale non plus dans la mesure où elle ne prend pas en compte la différence de température de l'eau. Je ne saurai pas dire laquelle est la plus fiable...!

En tout cas c'est top !

**Comment by stawen** [comment]
oui c'est ca, si la pompe tourne, la consommation de pellet est forcement pour l'eau chaude...donc ça me semble assez cohérent. il peut y  avoir un decalage avec l'allumage si chaudiere eteinte, mais dans mes graphes, j'ai l'iimpression que la pompe tourne quasiment dès que la chaudiere s'allume pour l'eau chaude.
Je pense que c'est un bon compromis

**Comment by stawen** [comment]
Dans le fonctionnement de la chaudière, de ce que j'ai pu voir, la pompe de chauffage ne tourne pas quand  la pompe ecs tourne. C'est un ou exclusif. (je n'ai pas vu de chaudière faire différemment pour le moment)

**Comment by bertrandgorge** [comment]
Non ce n'est pas exclusif - ça dépend un peu des réglages de la priorité ECS, etc..., mais typiquement chez moi j'ai des trucs comme ça : 

![image](https://user-images.githubusercontent.com/12585613/100775710-ecf5a580-3403-11eb-811b-28ae9014d9fe.png)

Mais je suis d'accord pour dire qu'en première approximation c'est pas mal.

**Comment by stawen** [comment]
close by #105
