### ISSUE TITLE
Consommation erronée lorsque silo considéré vide

### ISSUE THREAD

**Issue by yoanncapacites** [stawen/okovision#87]
Depuis 3 semaines, l'application pensait que mon silo était vide alors qu'il restait un fond de granulés utilisés pour l'eau chaude (chauffage coupé). Cependant, depuis que l'application pense que le silo est vide, malgré une consommation qui devrait être d'environ une dizaine de kilos, l'application affiche une consommation fausse de plus de 250kg par jour soit 2 fois plus qu'en plein hiver!
Est-il possible de corriger manuellement les jours ou le système a rentré de fausses informations?

**Comment by bertrandgorge** [comment]
Bonjour Yoann, je pense que tu as trouvé un joli cas limite ! Ca devrait être facile à corriger. Pour ça il faudra que tu ailles regarder dans ta DB (phpMyAdmin).

La table qui t'intéresse c'est oko_resume_day - là t'as une ligne par jour, vérifie celles qui correspondent aux valeurs délirantes. Tu peux les supprimer elles seront reconstruites automatiquement.

La deuxième table qui t'intéresse c'est oko_silo_events - c'est là où sont stockés les événements de remplissage du silo, entre autres. Il faut que tu modifie le dernier remplissage, pour ajouter un petit 100 ou 200kg dans le remaining. Comme ça okovision pensera qu'il reste bien du bois dans ton silo.

**Comment by yoanncapacites** [comment]
Bonjour Bertrand, merci pour ce retour rapide. J'ai mis à jour le titre du bug. En effet, suite au remplissage du silo, j'ai corrigé manuellement les données de la BDD et actualisé le stock du silo.
Cependant le bug était toujours présent. Il n'etait pas dû au "silo vide" mais a la lecture du fichier CSV.
En effet, suite probablement à une manipulation dont je ne me souviens plus, le fichier CSV a été modifié et une colonne a été ajoutée, ce que je ne pensais pas possible. En d'autres termes, okovision s'était mis à décaler les colonnes et utiliser par exemple les valeurs de la colonne PE1 Status à la place de PE1 Motor ES. J'ai mis à jour la Matrice de lecture du CSV, est tout s'est mis à refonctionner.

Voici comment je m'en suis rendu compte (si jamais quelqu'un a le même soucis):

Le fichier CSV indique que la chaudière possède différents statuts lors de sa mise en marche (colonne PE1 Status) allant de 1 à 5. Lorsque la chaudière n'est pas en fonctionnement, son statut est à la valeur 99.
Depuis le 28/04/20 à 16h30, Okovision fait un décalage entre les colonnes. Par exemple, lorsque j'affiche sur un graphique les valeurs qui correspondent à la colonne PE1 Motor ES (Moteur alimentation chaudière (On/Off) ), il y avait uniquement 0 ou 1 (donc Okovision trouvait la bonne colonne). Depuis le bug, lorsque je demande à afficher la colonne PE1 Motor ES, il affiche les valeurs de la colonne précédente (PE1 Status). Idem, PE1 Status affiche les valeurs de la colonne précédente.
